export const users = [
  {
    email: "user01@example.com",
    password: "Pass@01",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=1",
    name: "Nguyễn Văn An",
    phone: "0901000001",
    loyaltyPoints: 123,
    address: ["12 Lê Lợi", "Quận 1", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user02@example.com",
    password: "Pass@02",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=2",
    name: "Trần Thị Bích",
    phone: "0901000002",
    loyaltyPoints: 450,
    address: ["45 Nguyễn Trãi", "Quận 5", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user03@example.com",
    password: "Pass@03",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=3",
    name: "Lê Hoàng Cường",
    phone: "0901000003",
    loyaltyPoints: 78,
    address: ["9 Trần Phú", "Quận Hà Đông", "Hà Nội", "Vietnam"],
  },
  {
    email: "user04@example.com",
    password: "Pass@04",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=4",
    name: "Phạm Thị Dung",
    phone: "0901000004",
    loyaltyPoints: 670,
    address: ["88 Hoàng Hoa Thám", "Quận Ba Đình", "Hà Nội", "Vietnam"],
  },
  {
    email: "user05@example.com",
    password: "Pass@05",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=5",
    name: "Hoàng Minh Đức",
    phone: "0901000005",
    loyaltyPoints: 305,
    address: [
      "23 Phan Đình Phùng",
      "Quận Phú Nhuận",
      "Thành phố Hồ Chí Minh",
      "Vietnam",
    ],
  },
  {
    email: "user06@example.com",
    password: "Pass@06",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=6",
    name: "Đặng Thị Em",
    phone: "0901000006",
    loyaltyPoints: 12,
    address: [
      "120 Trần Hưng Đạo",
      "Quận 5",
      "Thành phố Hồ Chí Minh",
      "Vietnam",
    ],
  },
  {
    email: "user07@example.com",
    password: "Pass@07",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=7",
    name: "Vũ Quang Huy",
    phone: "0901000007",
    loyaltyPoints: 999,
    address: ["7 Ngô Quyền", "Quận Sơn Trà", "Đà Nẵng", "Vietnam"],
  },
  {
    email: "user08@example.com",
    password: "Pass@08",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=8",
    name: "Ngô Thị Hạnh",
    phone: "0901000008",
    loyaltyPoints: 240,
    address: ["56 Lý Thường Kiệt", "Quận Thanh Khê", "Đà Nẵng", "Vietnam"],
  },
  {
    email: "user09@example.com",
    password: "Pass@09",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=9",
    name: "Bùi Văn Khang",
    phone: "0901000009",
    loyaltyPoints: 412,
    address: ["18 Hùng Vương", "Thành phố Vinh", "Nghệ An", "Vietnam"],
  },
  {
    email: "user10@example.com",
    password: "Pass@10",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=10",
    name: " Trịnh Thị Lan",
    phone: "0901000010",
    loyaltyPoints: 87,
    address: ["2 Nguyễn Văn Cừ", "Quận Long Biên", "Hà Nội", "Vietnam"],
  },
  {
    email: "user11@example.com",
    password: "Pass@11",
    role: "STAFF",
    image: "https://i.pravatar.cc/150?img=11",
    name: "Phan Minh Lâm",
    phone: "0901000011",
    loyaltyPoints: 520,
    address: [
      "33 Cách Mạng Tháng 8",
      "Quận 3",
      "Thành phố Hồ Chí Minh",
      "Vietnam",
    ],
  },
  {
    email: "user12@example.com",
    password: "Pass@12",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=12",
    name: "Lương Thị Mai",
    phone: "0901000012",
    loyaltyPoints: 204,
    address: ["5 Trần Quốc Toản", "Quận Hồng Bàng", "Hải Phòng", "Vietnam"],
  },
  {
    email: "user13@example.com",
    password: "Pass@13",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=13",
    name: "Đỗ Văn Nam",
    phone: "0901000013",
    loyaltyPoints: 33,
    address: ["77 Phan Bội Châu", "Quận Hoàn Kiếm", "Hà Nội", "Vietnam"],
  },
  {
    email: "user14@example.com",
    password: "Pass@14",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=14",
    name: "Trương Thị Oanh",
    phone: "0901000014",
    loyaltyPoints: 601,
    address: ["10 Bùi Thị Xuân", "Quận Hai Bà Trưng", "Hà Nội", "Vietnam"],
  },
  {
    email: "user15@example.com",
    password: "Pass@15",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=15",
    name: "Văn Quý Phương",
    phone: "0901000015",
    loyaltyPoints: 150,
    address: ["200 Võ Văn Kiệt", "Quận 1", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user16@example.com",
    password: "Pass@16",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=16",
    name: "Nguyễn Thị Quỳnh",
    phone: "0901000016",
    loyaltyPoints: 88,
    address: [
      "14 Lê Hồng Phong",
      "Thành phố Vũng Tàu",
      "Bà Rịa - Vũng Tàu",
      "Vietnam",
    ],
  },
  {
    email: "user17@example.com",
    password: "Pass@17",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=17",
    name: "Hà Văn Sơn",
    phone: "0901000017",
    loyaltyPoints: 710,
    address: ["66 Lý Nam Đế", "Quận Hoàn Kiếm", "Hà Nội", "Vietnam"],
  },
  {
    email: "user18@example.com",
    password: "Pass@18",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=18",
    name: "Phùng Thị Thảo",
    phone: "0901000018",
    loyaltyPoints: 27,
    address: ["90 Nguyễn Huệ", "Quận 1", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user19@example.com",
    password: "Pass@19",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=19",
    name: "Đàm Minh Tú",
    phone: "0901000019",
    loyaltyPoints: 402,
    address: [
      "8 Phan Chu Trinh",
      "Thành phố Nha Trang",
      "Khánh Hòa",
      "Vietnam",
    ],
  },
  {
    email: "user20@example.com",
    password: "Pass@20",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=20",
    name: "Lê Thị Vinh",
    phone: "0901000020",
    loyaltyPoints: 5,
    address: ["3 Nguyễn Trãi", "Quận Hà Đông", "Hà Nội", "Vietnam"],
  },
  {
    email: "user21@example.com",
    password: "Pass@21",
    role: "STAFF",
    image: "https://i.pravatar.cc/150?img=21",
    name: "Phạm Quốc Vỹ",
    phone: "0901000021",
    loyaltyPoints: 315,
    address: ["44 Trần Nhân Tông", "Quận Hai Bà Trưng", "Hà Nội", "Vietnam"],
  },
  {
    email: "user22@example.com",
    password: "Pass@22",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=22",
    name: "Đỗ Thị Yến",
    phone: "0901000022",
    loyaltyPoints: 220,
    address: ["55 Lê Duẩn", "Quận 1", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user23@example.com",
    password: "Pass@23",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=23",
    name: "Nguyễn Văn Zed",
    phone: "0901000023",
    loyaltyPoints: 77,
    address: ["123 Hoàng Diệu", "Đà Lạt", "Lâm Đồng", "Vietnam"],
  },
  {
    email: "user24@example.com",
    password: "Pass@24",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=24",
    name: "Trần Phước An",
    phone: "0901000024",
    loyaltyPoints: 640,
    address: ["7 Trần Phú", "Quận Ninh Kiều", "Cần Thơ", "Vietnam"],
  },
  {
    email: "user25@example.com",
    password: "Pass@25",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=25",
    name: "Võ Thị Bảo",
    phone: "0901000025",
    loyaltyPoints: 299,
    address: ["9 Nguyễn Huệ", "Thành phố Quy Nhơn", "Bình Định", "Vietnam"],
  },
  {
    email: "user26@example.com",
    password: "Pass@26",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=26",
    name: "Bạch Quốc Cường",
    phone: "0901000026",
    loyaltyPoints: 89,
    address: [
      "20 Phan Đình Phùng",
      "Thành phố Huế",
      "Thừa Thiên Huế",
      "Vietnam",
    ],
  },
  {
    email: "user27@example.com",
    password: "Pass@27",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=27",
    name: "Lưu Thị Diễm",
    phone: "0901000027",
    loyaltyPoints: 478,
    address: ["88 Trần Phú", "Quận 10", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user28@example.com",
    password: "Pass@28",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=28",
    name: "Hồ Minh Giang",
    phone: "0901000028",
    loyaltyPoints: 155,
    address: ["15 Cầu Giấy", "Quận Cầu Giấy", "Hà Nội", "Vietnam"],
  },
  {
    email: "user29@example.com",
    password: "Pass@29",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=29",
    name: "Tạ Thị Hương",
    phone: "0901000029",
    loyaltyPoints: 33,
    address: ["31 Xuân Thủy", "Quận Tây Hồ", "Hà Nội", "Vietnam"],
  },
  {
    email: "user30@example.com",
    password: "Pass@30",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=30",
    name: "Chu Văn Khoa",
    phone: "0901000030",
    loyaltyPoints: 711,
    address: ["101 Võ Thị Sáu", "Quận 3", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user31@example.com",
    password: "Pass@31",
    role: "ADMIN",
    image: "https://i.pravatar.cc/150?img=31",
    name: "Nguyễn Quốc Long",
    phone: "0901000031",
    loyaltyPoints: 880,
    address: ["1 Trần Hưng Đạo", "Quận Hoàn Kiếm", "Hà Nội", "Vietnam"],
  },
  {
    email: "user32@example.com",
    password: "Pass@32",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=32",
    name: "Phạm Thị Minh",
    phone: "0901000032",
    loyaltyPoints: 47,
    address: ["60 Nguyễn Văn Trỗi", "Thành phố Pleiku", "Gia Lai", "Vietnam"],
  },
  {
    email: "user33@example.com",
    password: "Pass@33",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=33",
    name: "Đinh Thanh Nam",
    phone: "0901000033",
    loyaltyPoints: 261,
    address: ["77 Lê Lợi", "Quận 1", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user34@example.com",
    password: "Pass@34",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=34",
    name: "Ngô Thị Oanh",
    phone: "0901000034",
    loyaltyPoints: 92,
    address: [
      "14 Trần Quang Khải",
      "Quận 1",
      "Thành phố Hồ Chí Minh",
      "Vietnam",
    ],
  },
  {
    email: "user35@example.com",
    password: "Pass@35",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=35",
    name: "Trịnh Bá Phúc",
    phone: "0901000035",
    loyaltyPoints: 399,
    address: ["28 Nguyễn Chí Thanh", "Quận Đống Đa", "Hà Nội", "Vietnam"],
  },
  {
    email: "user36@example.com",
    password: "Pass@36",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=36",
    name: "Vũ Thị Quỳnh",
    phone: "0901000036",
    loyaltyPoints: 6,
    address: [
      "50 Phan Xích Long",
      "Quận Phú Nhuận",
      "Thành phố Hồ Chí Minh",
      "Vietnam",
    ],
  },
  {
    email: "user37@example.com",
    password: "Pass@37",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=37",
    name: "Lê Trọng Sơn",
    phone: "0901000037",
    loyaltyPoints: 525,
    address: [
      "12 Bạch Đằng",
      "Quận Bình Thạnh",
      "Thành phố Hồ Chí Minh",
      "Vietnam",
    ],
  },
  {
    email: "user38@example.com",
    password: "Pass@38",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=38",
    name: "Phan Thị Thanh",
    phone: "0901000038",
    loyaltyPoints: 210,
    address: ["66 Trần Hưng Đạo", "Quận Hoàng Mai", "Hà Nội", "Vietnam"],
  },
  {
    email: "user39@example.com",
    password: "Pass@39",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=39",
    name: "Đào Văn Tùng",
    phone: "0901000039",
    loyaltyPoints: 133,
    address: ["8 Nguyễn Văn Cừ", "Quận Long Biên", "Hà Nội", "Vietnam"],
  },
  {
    email: "user40@example.com",
    password: "Pass@40",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=40",
    name: "Hoàng Thị Uyên",
    phone: "0901000040",
    loyaltyPoints: 44,
    address: ["22 Hùng Vương", "Thành phố Thái Bình", "Thái Bình", "Vietnam"],
  },
  {
    email: "user41@example.com",
    password: "Pass@41",
    role: "STAFF",
    image: "https://i.pravatar.cc/150?img=41",
    name: "Nguyễn Hữu Vinh",
    phone: "0901000041",
    loyaltyPoints: 700,
    address: ["99 Trần Phú", "Thành phố Ninh Bình", "Ninh Bình", "Vietnam"],
  },
  {
    email: "user42@example.com",
    password: "Pass@42",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=42",
    name: "Trần Thị Xinh",
    phone: "0901000042",
    loyaltyPoints: 268,
    address: [
      "11 Đinh Tiên Hoàng",
      "Thành phố Huế",
      "Thừa Thiên Huế",
      "Vietnam",
    ],
  },
  {
    email: "user43@example.com",
    password: "Pass@43",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=43",
    name: "Văn Đức Yên",
    phone: "0901000043",
    loyaltyPoints: 19,
    address: ["37 Trần Phú", "Quận 5", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user44@example.com",
    password: "Pass@44",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=44",
    name: "Bùi Thị Zoa",
    phone: "0901000044",
    loyaltyPoints: 354,
    address: ["5 Nguyễn Tất Thành", "Quận Hải Châu", "Đà Nẵng", "Vietnam"],
  },
  {
    email: "user45@example.com",
    password: "Pass@45",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=45",
    name: "Phạm Thành Anh",
    phone: "0901000045",
    loyaltyPoints: 488,
    address: ["3 Nguyễn Huệ", "Quận 1", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user46@example.com",
    password: "Pass@46",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=46",
    name: "Đỗ Quốc Bình",
    phone: "0901000046",
    loyaltyPoints: 277,
    address: ["70 Lê Lợi", "Thành phố Vinh", "Nghệ An", "Vietnam"],
  },
  {
    email: "user47@example.com",
    password: "Pass@47",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=47",
    name: "Lê Minh Chi",
    phone: "0901000047",
    loyaltyPoints: 34,
    address: ["21 Trần Hưng Đạo", "Quận 1", "Thành phố Hồ Chí Minh", "Vietnam"],
  },
  {
    email: "user48@example.com",
    password: "Pass@48",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=48",
    name: "Hoàng Thị Duyên",
    phone: "0901000048",
    loyaltyPoints: 615,
    address: ["12 Phố Huế", "Quận Hai Bà Trưng", "Hà Nội", "Vietnam"],
  },
  {
    email: "user49@example.com",
    password: "Pass@49",
    role: "CUSTOMER",
    image: "https://i.pravatar.cc/150?img=49",
    name: "Phạm Văn E",
    phone: "0901000049",
    loyaltyPoints: 132,
    address: ["2 Lê Thanh Nghị", "Quận Hai Bà Trưng", "Hà Nội", "Vietnam"],
  },
  {
    email: "user50@example.com",
    password: "Pass@50",
    role: "ADMIN",
    image: "https://i.pravatar.cc/150?img=50",
    name: "Trương Quốc Z",
    phone: "0901000050",
    loyaltyPoints: 1000,
    address: ["10 Nguyễn Trãi", "Quận Thanh Xuân", "Hà Nội", "Vietnam"],
  },
];
